import HeaderResponsive from "@/components/layouts/Header/HeaderResponsive";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Book Store LyHoaiLam",
  description: "Generated by create next app",
};


export default function Layout({ children }: { children: React.ReactNode }) {
  return (
      <div id={'root-layout'}>
        <HeaderResponsive />
        <div className="mt-[150px]">
          {children}
        </div>
      </div>
  )
}
