import HeaderResponsive from "@/components/layouts/Header/HeaderResponsive";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Book Store LyHoaiLam",
  description: "Generated by create next app",
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
      <div>
        <HeaderResponsive />
        <div className="z-2">
          {children}
        </div>
      </div>
  )
}
