import type { Metadata } from "next";
import { Cherry_Swash } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import Footer from "@/components/layouts/Footer/Footer";
const cherrySwash = Cherry_Swash({
  variable: "--cherry-swash",
  subsets: ["latin"],
  weight: "400", // Font này chỉ có 1 weight
});
export const metadata: Metadata = {
  title: "Book Store LyHoaiLam",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${cherrySwash.variable} ${cherrySwash.variable}`} suppressHydrationWarning>
    <body className={`${cherrySwash.variable} ${cherrySwash.variable} antialiased`}>
      <div className="bg-red">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Toaster />
          <div className="mt-45">
            {children}
          </div>
        </ThemeProvider>
        <Footer />
      </div>
    </body>
  </html>
  )
}
